# 행렬 정의,접근,타입변환
- 2차원 행렬 np.array([ [],[],[] ])

- 1차원 벡터 np.array([])

In [2]:
import numpy as np

## real matrix
- double precision(float64) 

In [3]:
a=np.array([[1,2.5,3],[-1,0,-2],[4,5.5,6]],dtype=np.float64)

## complex matrix
- 실,허수 분리 저장(complex128)

- 허수:Xj 

- np.array([ [2+1j, 1-0j] ,[],[] ])

In [18]:
b=np.array([[+1j,2,3],[4,5+0j,3]], dtype=np.complex128)

## shape(tuple)

- a.shape  #(r,c) tuple , shape[0]==r

-벡터.shape #(x, )

In [22]:
print(a.shape) 
print(a.shape[0])
print(a.shape[1])

(3, 3)
3
3


## ValueChange
명시적 타입 변환 a.astype(dtype = np.complex128)

- 허->실 실수 부분만 남김

암묵적 타입변환 (행열 연산시 실행)

- var[0,0]  ~ var[i,j]

- 실수->실수 수정 가능, dtype=np.float64

- 실->허 dtype=np.complex64 OR 허수 표현 포함


In [ ]:
#(a[1,1]=0+0j 불가)
a[1,1]=0

In [25]:
#typechange
a=a.astype(dtype=np.complex128)
b=b.astype(dtype=np.float64) #실수잘림

# float+complex 연산시 complex128로 암묵적변환

### 연습문제

In [37]:
A=np.array([[1,2,4,1],[2,1,3,1],[5,2,1,4]], dtype=np.float64)
print(A.shape)
#A[1,2]=1+2i (error)
A[2,1]=0
print(A)

(3, 4)
[[1. 2. 4. 1.]
 [2. 1. 3. 1.]
 [5. 0. 1. 4.]]


# 행렬 입출력(txt)

## input

- np.genfromtxt('파일이름.txt',dtype=데이터타입 수정 ,delimiter='구분방법')

In [43]:
a=np.genfromtxt('input1.txt',delimiter='',dtype=np.float64) #구분기호
print(a)

[[ 1.   2.4  3. ]
 [-1.2  3.3  4.3]
 [-1.3  0.2  0. ]]


In [46]:
b=np.genfromtxt('cinput1.txt',delimiter=',',dtype=np.complex128)
print(b)

[1.-2.j 3.+1.j 1.+0.j]


## formatting output
- floating format : "%0.4f"

- scientific format : "%0.2e" (15자리 이상 출력 무의미)


- np.savetxt("파일이름",행렬,fmt="%0.4f",delimiter=",")

In [52]:
np.savetxt('output1.txt',a,delimiter='',fmt="%0.4f")

## custom
- from print_lecture import print_custom as prt

- prt(행렬,fmr="",delimiter='')

## 연습문제

In [35]:
#practice1
a=np.random.rand(4,6)
np.savetxt('inp_pr1.txt',a,delimiter='',fmt="%0.1e")

#practice 2
b=np.genfromtxt('inp_pr2a.txt',delimiter='')
print(b)
print(b.shape)

[1. 2. 3.]
(3,)


# numpy 기능

## eye,identity Band 개념
 - np.eye : band에 1채워넣기 (대각선)
 - a=np.eye(row,col,band id(0).dtype=선택) 
 
 - np.identity: identity matrix
 - a=np.identity(3, dtype=선택)

In [11]:
a1=np.eye(3,4,k=0,dtype=np.float64)
a2=np.eye(4,3,k=1, dtype=np.complex128)
a3=np.identity(3)

print(a1)
print(a2)
print(a3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## tri 삼각행렬
- np.tri: lower triangular matrix nonzero entry=1  (k<= band id) 


In [15]:
t1=np.tri(4,3,k=-1)
t2=np.tri(4,4, k=0)
print(t1)
print(t2)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


## zeros, ones, full
- np.zeros:0으로 채움 np.zeros(shape(tuple))
-np.ones:1로 채움 np.ones(shape(tuple))
-np.full:지정값으로 채움 np.full(shape(tuple),value)

In [24]:
sh=(2,3)
zr=np.zeros(sh, dtype=np.complex128)
on=np.ones(sh)
fu=np.full((3,3),1+1j) #vector (5,) 가능

print(zr)
print(on)
print(fu)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.+1.j 1.+1.j 1.+1.j]
 [1.+1.j 1.+1.j 1.+1.j]
 [1.+1.j 1.+1.j 1.+1.j]]


## random
- np.random.rand ==> real matrix(np.float64) , between 0,1
- np.random.rand(row,col) 

In [27]:
ran=np.random.rand(3,4)
print(ran)

[[0.9835509  0.56961365 0.55460027 0.80958942]
 [0.9811221  0.44561729 0.21621562 0.72490515]
 [0.41024044 0.29023715 0.31590322 0.42708394]]


## 연습문제

In [36]:
#practice 1
f1=np.identity(20)
np.savetxt('f1output.txt',f1,delimiter='',fmt="%0.1f")

#practice 2
r1=np.random.rand(3,3)
r1.astype(dtype=np.complex128)
print(r1)

[[0.67035675 0.55565126 0.81137229]
 [0.75180345 0.75387227 0.63970379]
 [0.78221491 0.75838188 0.23798209]]


# 행렬 기본조작1

## copy (카피)
- 행렬을 대입했을때 두 행렬이 같은 메모리 참조(복사X)
- b=np.copy(a)

In [42]:
a=np.array([[1,2.5,3],[-1,1,-2],[4,5.5,6]],dtype=np.float64)
b=np.copy(a)
a[1,1]=0.0

print(a)
print(b)

[[ 1.   2.5  3. ]
 [-1.   0.  -2. ]
 [ 4.   5.5  6. ]]
[[ 1.   2.5  3. ]
 [-1.   1.  -2. ]
 [ 4.   5.5  6. ]]


## reshape (공유)
- b=np.reshape(a,tuple vector OR shape) =>a원본 그대로, 같은 메모리공간 참조
- all entry 개수 맞아야함 3,2 -> 2,3 OR 6

In [46]:
a=np.array([[1,2.5,3],[-1,1,-2]],dtype=np.float64)
b=np.reshape(a,6)
c=np.reshape(a,(3,2))

print(a)
print(b)
print(c)

[[ 1.   2.5  3. ]
 [-1.   1.  -2. ]]
[ 1.   2.5  3.  -1.   1.  -2. ]
[[ 1.   2.5]
 [ 3.  -1. ]
 [ 1.  -2. ]]


## tril, triu (카피)
-b=np.tril(a,k=band_id)   Band id 포함 lower 부분 copy

-b=np.triu(a,k=band_id)   Band id 포함 upper 부분 copy

In [53]:
a=np.array([[1,2,3,],[4,5,6],[7,8,9]])
b=np.tril(a,k=0)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


## diag (공유)
- band 뽑아 벡터로 만들기 READ-ONLY 편집불가
- b=np.diag(a, k=band_id)
- 벡터를 받았을 때 정사각형 행렬 생성 (생성한 정사각형 행렬은 독립메모리)

In [56]:
b=np.diag(a, k=0)
print(b)

[1 5 9]


In [61]:
b=np.array([1,2,3,4])
a=np.diag(b,k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## diagflat (카피)
- np.diagflat(array, k=band_id)
- array를 벡터화 한 다음 정사각형 행렬 생성

In [69]:
M=np.array([[1,3],[2,4]])
d=np.diagflat(M,k=0)

M[1,1]=0
print(M)
print(d)

[[1 3]
 [2 0]]
[[1 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 4]]


## trace
- np.trace (a, offset=band_id) 
- band_id entry 더한 값 OR 0이거나 생략시 주대각선 합

In [70]:
val=np.trace(a,offset=-1)
print(val)

10


## flatten()(공유), ravel (카피)
- b=a.flatten() => 행렬 a를 벡터화해서 copy
- b=a.ravel() => 행렬 a를 벡터화해서 공유

In [75]:
a=np.array([[1,2,3,],[4,5,6],[7,8,9]])
b=a.flatten()
c=a.ravel()

a[1,1]=0

print(a)
print(b)
print(c)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 0 6 7 8 9]


## 연습문제

In [97]:
#practixe 1
p1=np.genfromtxt('inp_pr1.txt',delimiter='')

pco=np.copy(np.reshape(p1,(5,3)))
bt=np.triu(pco,k=0)
btre=np.copy(np.reshape(bt,15))
bts=np.diagflat(btre,k=0)
tr=np.trace(bts,offset=0)

print(pco)
print(bt)
print(btre)
print(bts)
print(tr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [0. 1. 2.]
 [3. 4. 5.]]
[[1. 2. 3.]
 [0. 5. 6.]
 [0. 0. 9.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 2. 3. 0. 5. 6. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
26.0


# 행렬 기본조작 2

## hstack(수평), vstack(수직)
### 행렬
- np.hstack(tuple) => 행(row,shape[0])개수 같아야함 
- np.vstack(tuple) => 열(col,shape[1]) 개수 같아야함

### 벡터
- np.hstack(tuple) => 더 길어진 벡터 (row)
- np.vstack(tuple) => 수직으로 쌓아 행렬 생성

### 혼합
- np.vstack(tuple)

In [100]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[7,6,8],[2,6,3]])

new=np.hstack((a,b))
print(new)

[[1 2 3 7 6 8]
 [2 3 4 2 6 3]]


## transpose (공유)
- b=a.transpose() 
- 벡터일때는 그대로 나옴

In [102]:
b=a.transpose()
print(b)

[[1 2]
 [2 3]
 [3 4]]


## real(공유), imag(공유), conjugate()(카피)
- b.real  실수
-b.imag 허수( 실수행렬,벡터)
-b=a.conjugate()

In [108]:
a=np.array([[1-2j,3+1j,1],[1+2j,2-1j,7]])

ar=a.real
ai=a.imag
ac=a.conjugate()

a[0,0]=100+1j
print(ar)
print(ai)
print(ac)

[[100.   3.   1.]
 [  1.   2.   7.]]
[[ 1.  1.  0.]
 [ 2. -1.  0.]]
[[1.+2.j 3.-1.j 1.-0.j]
 [1.-2.j 2.+1.j 7.-0.j]]


## Multiplication
### Scalar 
- a*b

### Matrix & Matrix-vector product
- a@b
- np.matmul(A,B) A의 행개수와 B의 열 개수가 같아야함


In [111]:
r=3
result=a*r

b=np.array([[1-2j],[2-1j],[3]])

result2=a@b

print(result)
print(result2)

[[300.+3.j   9.+3.j   3.+0.j]
 [  3.+6.j   6.-3.j  21.+0.j]]
[[112.-200.j]
 [ 29.  -4.j]]


## vdot
- inner product (내적)
- re=np.vdot(u,v) ->complex 일때 conjugate 빠짐


## Norm (1,2,inf)
-from scipy import linalg

## 인덱싱으로 행렬 일부 뽑기 (공유)
-sub=a[1:3,1:4] => row(1,2) col(1,2,3)인 행렬

## 연습문제

In [134]:
#practice 1
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[-1,-2,-3,-4,-5]])

v1=a[0:4,1]
v2=a[0:4,2]
v3=a[0:4,3]

b=np.vstack((v1,v2,v3))
result=b@v1

print(b)
print(result)

[[ 2  7 12 -2]
 [ 3  8 13 -3]
 [ 4  9 14 -4]]
[201 224 247]


# 행렬 기본조작 3

## 덧셈,뺄셈 (shape 동일)
- c=a+b
- c=a-b

In [120]:
v1=np.diag((np.ones((4,))*(-1)),k=-1)
v2=np.diag(np.ones((5,))*2)
v3=np.diag(np.ones((4,)),k=1)

a=v1+v2+v3

print(a)

[[ 2.  1.  0.  0.  0.]
 [-1.  2.  1.  0.  0.]
 [ 0. -1.  2.  1.  0.]
 [ 0.  0. -1.  2.  1.]
 [ 0.  0.  0. -1.  2.]]


## Scalar+Matrix
- re=a+r
- all entry 에 r 더하기

In [122]:
r=2
re=a+r

print(re)

[[4. 3. 2. 2. 2.]
 [1. 4. 3. 2. 2.]
 [2. 1. 4. 3. 2.]
 [2. 2. 1. 4. 3.]
 [2. 2. 2. 1. 4.]]


## Matrix OR Vector*Matrix  OR /  
- 행렬의 열개수와 벡터의 사이즈 동일
- re=a*b
- all entry 각각 곱하기 
-2x2 * 2size 벡터일때 shape[1]에 벡터 곱함 , 나누기는 모두

## 행렬 일부 뽑아 행렬 만들기(카피)
- w= a[[1,2,0,3]:] -> 행 순서
- w= a[:[0,1,2,3]] -> 열 순서
- w= a[[1,2,0,3]:][:[0,1,2,3]] -> 행,열 순서